### ISSUE TITLE
pgbouncer is still used when it is disabled

### ISSUE THREAD

**Issue by gajus** [PostHog/charts-clickhouse#413] opened 2022-06-02 00:16 UTC
## Bug description

Configuration includes:

```
pgbouncer:
  enabled: false
```

Migrate job is failing with:

```
nc: bad address 'contra-posthog-pgbouncer.contra.svc.cluster.local'
waiting for PgBouncer
nc: bad address 'contra-posthog-pgbouncer.contra.svc.cluster.local'
waiting for PgBouncer
nc: bad address 'contra-posthog-pgbouncer.contra.svc.cluster.local'
waiting for PgBouncer
nc: bad address 'contra-posthog-pgbouncer.contra.svc.cluster.local'
waiting for PgBouncer
nc: bad address 'contra-posthog-pgbouncer.contra.svc.cluster.local'
```

I would expect all jobs to use `externalPostgresql`

**Comment by macobo** [comment] 2022-06-02 08:24
Related: https://github.com/PostHog/charts-clickhouse/issues/280

**Comment by guidoiaquinti** [comment] 2022-06-02 08:55
👋 Hi again @gajus, as Karl wrote above this is a known issue. I'm closing this as it is a duplicate of #280. 

Please let us know if we've missed anything. Thank you!

**Closed by guidoiaquinti** 2022-06-02 08:55 UTC
Labels: bug
