### ISSUE TITLE
Email setup from the PostHog app

### ISSUE THREAD

**Issue by tiina303** [PostHog/charts-clickhouse#114] opened 2021-09-06 22:42 UTC
## Is your feature request related to a problem?

Currently in order to have email available for password reset etc it needs to be set in the values.

## Describe the solution you'd like

Ability to set the email config in the PostHog app.

## Describe alternatives you've considered

As is.

## Additional context

In order for the email to stick around during upgrades etc we'll need to store the account info in the (Postgres) DB as we can't create a k8s secret from the app afaik.

**Comment by tiina303** [comment] 2022-01-25 21:31
@paolodamico has been working on this, not sure if there was an issue tracking it already?

**Comment by guidoiaquinti** [comment] 2022-02-02 17:32
@hazzadous I'm inclined to close this as part of https://github.com/PostHog/charts-clickhouse/pull/286. What do you think?

**Comment by hazzadous** [comment] 2022-02-02 17:41
I think this is actually a different issue @guidoiaquinti , assuming that the other linked PR is relevant. i.e. the desire is to setup email via the app UI(?)

**Comment by guidoiaquinti** [comment] 2022-02-02 17:44
Yes but I think it was to avoid passing email settings via env variables, right @tiina303 ?

If yes, this issue should be in `posthog/posthog`

**Comment by tiina303** [comment] 2022-02-02 21:15
In order to not need to pass email via envs here we needed it to be in the app. Not sure if we should keep the email/pass env option in the chart - it would be nice to be able to put them there for folks who setup multiple instances via automation but having a password as raw text might not be what we want to be doing. Happy to leave this for @guidoiaquinti & @hazzadous to decide.

**Comment by hazzadous** [comment] 2022-02-03 07:31
@tiina303 it's great for reproducible environments, which is the reason I put in the fix. The fix I've put in is actually to make it such that we don't need to expose CI for deploy at least to these secrets, and rather [provision a k8s secret separately](https://github.com/PostHog/posthog-cloud-infra/blob/main/terraform/modules/posthog/main.tf#L107)

Having these passed as env vars to the app I think is ok, but maybe there's a better way?

**Comment by guidoiaquinti** [comment] 2022-02-03 09:31
I also think we should keep the ability to configure email settings via ENV variables as it’s good for several use cases.

My main question is if: 

> Ability to set the email config in the PostHog app.

is something belonging to this repo or not? My take is that it doesn’t as the solution described in this ticket is a PostHog app feature. In that case, we should simply close this issue.

**Closed** 2022-02-03 21:58 UTC
Labels: enhancement, P2
