### ISSUE TITLE
ingress.enabled: false fails due to a missing gke-cert

### ISSUE THREAD

**Issue by gajus** [PostHog/charts-clickhouse#409] opened 2022-06-01 22:29 UTC
## Bug description

When `ingress.enabled: false`, then Helm deployment fails due to a missing `*-gke-cert`.

The full configuration:

```yaml
cloud: gcp
ingress:
  enabled: false
```

## Expected behavior

Expected PostHog to deploy.

## Actual behavior

Sync fails with `contra-posthog-gke-cert` Not Found error.

## How to reproduce

1. Deploy the shared configuration

## Environment

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): _please provide_
- [ ] k8s version (server version from `kubectl version`): _please provide_
- [ ] Chart version/commit (`helm list -n posthog`): _please provide_
- [ ] Posthog version: _please provide_

## Additional context

It looks like it is simply missing a condition in https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/gke-cert-issuer.yaml

**Comment by gajus** [comment] 2022-06-01 22:30
A temporary workaround is to provide a dummy ingress type, e.g. `ingress.type: 'disabled'`.

**Comment by guidoiaquinti** [comment] 2022-06-02 08:13
👋 Hi @gajus, thank you for your report. We currently do not officially support custom ingress resources if you want to self-host PostHog. We do that in order to simplify and standardise the cluster configuration we need to support. 

If you are on GCP, take a look at our [documentation](https://posthog.com/docs/self-host/deploy/gcp).

**Comment by guidoiaquinti** [comment] 2022-06-15 15:33
Hey @gajus I've tried to contact you multiple times without success. I'm going to close this as won't fix as the behaviour is as by design (see our docs). Feel free to ping me or re-open this issue if something is not clear. 

Thank you!

**Closed by guidoiaquinti** 2022-06-15 15:33 UTC
Labels: bug
