### ISSUE TITLE
Add PodDisruptionBudget for replicated components

### ISSUE THREAD

**Issue by Legion2** [PostHog/charts-clickhouse#216] opened 2021-12-06 15:56 UTC
### Proposed change
Add `PodDisruptionBudget` for all deployments. The PDB should be enabled if there are more then 1 replicas configured (`replicascount` or `hpa.minpods` > 1) for the component. The PDB makes the components more reliable during node maintenance, scaling and eviction.

### Alternative options
The user must create and maintain the PDB by themselves.

## Additional context
PDB can be enabled if there are more than 1 replica or with a configuration option.

**Comment by guidoiaquinti** [comment] 2021-12-22 11:02
Duplicate of #158. I'm going to add some additional context there and closing this issue 🧹

**Closed by guidoiaquinti** 2021-12-22 11:02 UTC
Labels: enhancement
