### ISSUE TITLE
clickhouse.enabled: false creates clickhouseinstall CRDs

### ISSUE THREAD

**Issue by gajus** [PostHog/charts-clickhouse#410] opened 2022-06-01 23:51 UTC
## Bug description

clickhouse.enabled: false creates clickhouseinstall CRDs

## Expected behavior

I would not expect CRDs to be created.

## Actual behavior

<img width="525" alt="Screen Shot 2022-06-01 at 6 50 34 PM" src="https://user-images.githubusercontent.com/973543/171519841-8e31620b-749e-4ad4-8147-50b5bf4fecb0.png">

## How to reproduce

1. use provided config

## Environment

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): _please provide_
- [ ] k8s version (server version from `kubectl version`): _please provide_
- [ ] Chart version/commit (`helm list -n posthog`): _please provide_
- [ ] Posthog version: _please provide_

**Comment by guidoiaquinti** [comment] 2022-06-02 08:23
👋 Hi again @gajus. This is true but it is unfortunately a limitation of Helm + how we package upstream resources from [Altinity/clickhouse-operator](https://github.com/Altinity/clickhouse-operator) as they don't offer (yet) a Helm chart (see https://github.com/Altinity/clickhouse-operator/pull/836, https://github.com/Altinity/clickhouse-operator/issues/837, https://github.com/Altinity/clickhouse-operator/issues/941).

If you want to skip the the CRD installation, my suggestion is to pass `--skip-crds` to your Helm command.

Here below is a better explanation of the problem from the [Helm official documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/):

> With the arrival of Helm 3, we removed the old `crd-install` hooks for a more simple methodology. There is now a special directory called `crds` that you can create in your chart to hold your CRDs. These CRDs are not templated, but will be installed by default when running a helm install for the chart. If the CRD already exists, it will be skipped with a warning. If you wish to skip the CRD installation step, you can pass the `--skip-crds` flag.
> 
> **Some caveats (and explanations)**
> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.
> 
> The `--dry-run` flag of helm install and helm upgrade is not currently supported for CRDs. The purpose of "Dry Run" is to validate that the output of the chart will actually work if sent to the server. But CRDs are a modification of the server's behavior. Helm cannot install the CRD on a dry run, so the discovery client will not know about that Custom Resource (CR), and validation will fail. You can alternatively move the CRDs to their own chart or use helm template instead.
> 
> Another important point to consider in the discussion around CRD support is how the rendering of templates is handled. One of the distinct disadvantages of the crd-install method used in Helm 2 was the inability to properly validate charts due to changing API availability (a CRD is actually adding another available API to your Kubernetes cluster). If a chart installed a CRD, helm no longer had a valid set of API versions to work against. This is also the reason behind removing templating support from CRDs. With the new crds method of CRD installation, we now ensure that helm has completely valid information about the current state of the cluster.

**Comment by guidoiaquinti** [comment] 2022-06-15 15:32
Hey @gajus I've tried to contact you multiple times without success. I'm going to close this as won't fix as the behaviour is as by design. Feel free to ping me or re-open this issue if something is not clear. 

Thank you!

**Closed by guidoiaquinti** 2022-06-15 15:32 UTC
Labels: bug
